language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25

jdk:
  - oraclejdk8

script:
  - ./gradlew clean :kotlincursor-compiler:jar :kotlincursor-compiler:test

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "GI8QorRX4MtGvojkjmlZm5ruGyr0ZN87dRQuqwQLBlEyraN0Z8wOioCyuszrWWyfxeF+eKjD0wnUFaoy9R65eVRepDWsgD0mC6hiwCYDbOTsaGucYu0vz4YK9/n+4FR7CHAyvCBVyzBf2zwwM/WRMZ5TmV6xkbrAdGGQ19c/QiONyKC3knLJVpnAr4b8n/j9H3QtB4sXL1WNbR00V3yzlQm1nM6ClKbnigIEeCHZIF9qB3CqZaRnxU+36Txf6Fm+6GPynxyQtzXUDMWXIcXzOsCIBzYbL/oukJ+HCYLiaV3ihPgIhBYHEH0OAqIww95cskX1LBd4688pdc8NmrYfhDw4fhUSfdRguT/xrk33/rWD0AoMiMOSSG4rBLa7XC6BB72uP+UqQabQIWF8LQ3zoJh9nRJbS5EG790KsGUFCUtpbNMiEN+jk/07Q0fQ6oTz7L3XKQcN0mcNoQys1VS8p7aRPK/KEAQNuij6uLAkx5PEGP0ueyjAHPsCE5OAjmBo4w7gTeA1BMytVPqUS14wpOjA5BQ7CbN9bGrPxnWQzt6oDeixyeLm8VIGcTgPiv00CuifrdAFMSU13lxObPhRm4PCRSJbI0IW0oUknm1Kxzx3z3XMmgScKraVV13na1GZyTImRkVqAnpKR9K6rVhw0BilTjueaxPUDYKKNYykXmo="
    - secure: "gyvMD/3fpx9KSr9Qi/Bf2UUtFLNAdC8e4TAElUOY/w49JkEuwEXb61mrvw34sm5oGMeDDx13Y7fmzO4jRPjFb8zXbGjUV7RV4NR9Jh8xnnYIqr2haJRogma0TH8WgLHXVQTmYZ+uCmeauEcthgMUjhQNfMnFZxzL5Avto2S4GdnK07tm3EAJo495h7/74bfXTGMfo2ikGZ702wmP6EH84cls7IKcb2oHbEQgAaaX+PZ1+RHp6U88UAxlP5hXTHqpPm9yy8f9D4X/qth2bL2/H7cAOKmxP5+tttBP7+gh9ftGE/qWhBIMmfRUhG6Nj5fzTyI2O+sSXwwYNgS8ds62bzTeRuZDmlgo3oP1iSB5MrIsJ0hVXfr02TALfHYOK28kiktlbU8QDz8omAInGRjiif+9HXgaJHIrTbR60YlyBTNoubEmrFS2tnR+Hxod925p4geUyac13JznGjdHZi1jdnXZfmULi/Fhq6drk/caTYseogEqUtqDr+YU8Z3ImJ7B016sRhPy5Kbd8hvLu8CN9ZnnFZQy/hOidtxL7hHQruiGqIPtrtNCt6Sd33BMFIiJEAXgFWB08MWn2vH0lmndplrkz7+5qm7P+1O4oOT76F+1cC516NndM7ChZHHuZ5gy3snaIHzqK3kC5r28lyZoGTNgcl/PrsPyCRJt0j96hXw="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle